# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b49dac9c42dbfd45e8b75b4d2aa6d93d"
name = "mersivx-builder-app"
application_url = "https://mersivx-shopify-admin-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Required scopes for reading shop data
scopes = "read_products,read_orders,read_discounts"

[auth]
redirect_urls = [
  "https://mersivx-shopify-admin-app.onrender.com/auth/callback",
  "https://mersivx-shopify-admin-app.onrender.com/auth/shopify/callback",
  "https://mersivx-shopify-admin-app.onrender.com/api/auth"
]

[distribution]
type = "custom"
